-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
CREATE TABLE FIRE_CAUSE (
    ID SERIAL PRIMARY KEY,
    CAUSE_ID int   NOT NULL,
    CAUSE_DESCRIPTION varchar   NOT NULL,
	UNIQUE (CAUSE_ID)
);


CREATE TABLE FIRE_INCIDENTS (
    ID SERIAL PRIMARY KEY,
    FIRE_NAME varchar   NOT NULL,
    FIRE_STARTED_DATE DATE   NOT NULL,
    FIRE_EXTINGUISHED_DATE DATE   NOT NULL,
    ARCHIVE_YEAR int   NOT NULL,
    COUNTY_ID VARCHAR   NOT NULL,
	STATE VARCHAR NOT NULL,
	CAUSE_ID int,
	CAUSE_DESCRIPTION VARCHAR,
    PERCENT_CONTAINED int   NOT NULL,
    TOTAL_ACRES_BURNED int   NOT NULL,
    MAJOR_INCIDENT boolean   NOT NULL,
    UNIQUE (FIRE_NAME),
	FOREIGN KEY (CAUSE_ID) REFERENCES FIRE_CAUSE (CAUSE_ID)
);


CREATE TABLE FIRE_IMPACTS (
    ID SERIAL PRIMARY KEY,
    FIRE_NAME varchar   NOT NULL,
    TOTAL_ACRES_BURNED int   NOT NULL,
    COUNTY_ID VARCHAR   NOT NULL,
    INJURIES int,
    STRUCTURE_IMPACTED  int,
	FOREIGN KEY (FIRE_NAME) REFERENCES FIRE_INCIDENTS (FIRE_NAME)
);

CREATE TABLE FIRE_LOCATIONS (
	ID SERIAL PRIMARY KEY,
    FIRE_NAME varchar   NOT NULL,
    COUNTY_ID VARCHAR   NOT NULL,
    COUNTY_NAME varchar   NOT NULL,
	LOCATION varchar,
    LATITUDE decimal   NOT NULL,
    LONGITUDE decimal   NOT NULL,
    MINIMUM_TEMP decimal   NOT NULL,
    MAXIMUM_TEMP decimal   NOT NULL,
	AVERAGE_TEMP decimal NOT NULL,
    WIND_SPEED decimal   NOT NULL,
	AIR_PRESSURE decimal NOT NULL,
	PRECIPITATION decimal NOT NULL,
	FOREIGN KEY (FIRE_NAME) REFERENCES FIRE_INCIDENTS (FIRE_NAME)

);


ALTER TABLE FIRE_IMPACTS ADD CONSTRAINT fk_FIRE_IMPACTS_FIRE_NAME FOREIGN KEY(FIRE_NAME)
REFERENCES FIRE_INCIDENTS (FIRE_NAME);

ALTER TABLE FIRE_LOCATIONS ADD CONSTRAINT fk_FIRE_LOCATIONS_FIRE_NAME_COUNTY_ID FOREIGN KEY(FIRE_NAME)
REFERENCES FIRE_INCIDENTS (FIRE_NAME);

